---
title: "Make clean valleys"
author: "Galen Holt"
format: html
editor: visual
---

## Default spatial data creation

We want a default data layer ltimNoNorth that is the CEWH-defined ltim valleys without the Northern Unregulated polygon, since that is overlain on the main set of catchments.

```{r}
library(sf)
```

Define where the shapefiles are- they're held externally. Use the `directorySet` framework for this.

```{r}
source('directorySet.R')
commonCRS <- 3577
```

```{r}
    # Get the LTIM_Valleys to use to subset for toy models at scale, but not enormous scale
    LTIM_Valleys <- read_sf(dsn = file.path(datDir,
                                            'ANAE/MDB_ANAE_Aug2017/MDB_ANAE.gdb'),
                            layer = 'LTIM_Valleys') |>
      st_cast("MULTIPOLYGON") |> # cleans up an issue with multisurfaces
      st_transform(crs = commonCRS) |>
      st_make_valid()
```

```{r}
# LTIM areas
ltimNoNorth <- LTIM_Valleys |>
  dplyr::select(ValleyName, ValleyID, ValleyCode) |> 
  dplyr::filter(ValleyName != 'Northern Unregulated')


```

```{r}
usethis::use_data(ltimNoNorth)
```
